// react/src/pages/Home.tsx
import {Jumbotron} from "../layout/Jumbotron.tsx";
import {useEffect, useState} from "react";
import axios from "axios"

interface Posts {
    title: string;
    id: number;
    thumbnail: string;
}

export function Home() {

    const [posts, setPosts] = useState<Posts[]>([]);

    const getPosts = () => {
        return axios('https://jsonplaceholder.typicode.com/posts').then(res => {
            const data = res.data.slice(0, 10)
            getPhotos(data);
        });
    }

    const getPhotos = (posts: Posts[]) => {
        return axios('https://jsonplaceholder.typicode.com/photos').then(res => {
            let data = res.data;
            data = data.splice(0, 10);
            posts.map((_post, key) => {
                    posts[key].thumbnail = data[key].thumbnailUrl;
            })
            setPosts(posts)
        });
    }

    useEffect(() => {
        getPosts();
    }, []);

    return (
        <>
            <Jumbotron title="Title of a longer featured blog post" text="Multiple lines of text that form the lede, informing new readers quickly
                        and efficiently about what’s most interesting in this post’s contents."/>

            <div className="row mb-2">
                {posts.map((post) => (
                    <div className="col-md-6" key={post.id}>
                        <div
                            className="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div className="col p-4 d-flex flex-column position-static">
                                <h3 className="mb-0">{post.title}</h3>
                                <div className="mb-1 text-body-secondary">Nov 12</div>
                                <p className="card-text mb-auto">This is a wider card with supporting text below as a
                                    natural lead-in to additional content.</p>
                                <a href="#" className="icon-link gap-1 icon-link-hover stretched-link">
                                    Continue reading
                                </a>
                            </div>
                            <div className="col-auto d-none d-lg-block">
                                <img src={ post.thumbnail ? post.thumbnail : 'https://placehold.co/150' } alt="thumbnail"/>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

        </>
    )
}

// angular/src/app/pages/home/home.component.ts
import { Component, NgModule, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { PostService } from '../../services/post/post.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent {
// mvc
// model view controller

  postService = inject(PostService)

  input = "";
  text = "The boy is going to school"

  changeText() {
    this.text = !this.input ? this.text : this.input
  }

  fetchPosts() {
    this.postService.getPost().subscribe(res => {
      console.log(res);
      
    })
  }

}

<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
      <h1 class="display-4 fst-italic">{{ text }}</h1>
      <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
      <form class="d-flex" role="search">
        <input [(ngModel)]="input" name="input" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" (click)="changeText()" type="button">Change Text</button>
      </form>
      <p class="lead mb-0"><a href="javascript:;" class="text-body-emphasis fw-bold">Continue reading...</a></p>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">World</strong>
          <h3 class="mb-0">Featured post</h3>
          <div class="mb-1 text-body-secondary">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="icon-link gap-1 icon-link-hover stretched-link">
            Continue reading
            <svg class="bi"><use xlink:href="#chevron-right"></use></svg>
          </a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success-emphasis">Design</strong>
          <h3 class="mb-0">Post title</h3>
          <div class="mb-1 text-body-secondary">Nov 11</div>
          <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="icon-link gap-1 icon-link-hover stretched-link">
            Continue reading
            <svg class="bi"><use xlink:href="#chevron-right"></use></svg>
          </a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
      </div>
    </div>
  </div>
