// vue/src/pages/Home.vue
<script>
import Jumbotron from "../components/Jumbotron.vue";
import Button from "../components/Button.vue";
import axios from "axios"

export default {
  name: 'Home',
  components: {
    Jumbotron, Button
  },
  data() {
    return {
      msg: "Welcome to the Vue.js application!",
      posts: [],
      photos: []
    }
  },
  methods: {
    changeMessage(newMessage) {
      this.msg = newMessage;
    }
  },
  async mounted() {
    this.posts = (await axios('https://jsonplaceholder.typicode.com/posts')).data.slice(0, 10);
    this.photos = (await axios('https://jsonplaceholder.typicode.com/photos')).data.slice(0, 10);
    this.posts.map((_post, key) => {
      this.posts[key].thumbnail = this.photos[key].thumbnailUrl;
    })
  }
}
</script>

<template>

  <Jumbotron title="Home page" text="Welcome to the Vue.js application!" />
<!--  {{ msg }}
  <br>
  <Button text="Click me" type="btn-danger" @click="changeMessage('This is a vue application!')"  />-->
  <div class="row">
    <div v-if="posts.length" v-for="post in posts" class="col-md-6" :key="post.id">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{ post.title }}</h3>
          <div class="mb-1 text-body-secondary">Nov 12</div>
          <p class="card-text mb-auto">{{ post.body }}</p>
          <router-link :to="`/posts/${post.id}`" class="icon-link gap-1 icon-link-hover stretched-link">
            Continue reading
          </router-link>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img :src="post.thumbnail" v-if="post.thumbnail" :alt="post.title"/>
          <img src='https://placehold.co/150' v-else/>
        </div>
      </div>
    </div>
    <div v-else>Loading posts...</div>
  </div>
</template>

// react/src/pages/Home.tsx
import {Jumbotron} from "../layout/Jumbotron.tsx";
import {useEffect, useState} from "react";
import axios from "axios"

interface Posts {
    title: string;
    id: number;
    thumbnail: string;
}

export function Home() {

    const [posts, setPosts] = useState<Posts[]>([]);

    const getPosts = () => {
        return axios('https://jsonplaceholder.typicode.com/posts').then(res => {
            const data = res.data.slice(0, 10)
            getPhotos(data);
        });
    }

    const getPhotos = (posts: Posts[]) => {
        return axios('https://jsonplaceholder.typicode.com/photos').then(res => {
            let data = res.data;
            data = data.splice(0, 10);
            posts.map((_post, key) => {
                    posts[key].thumbnail = data[key].thumbnailUrl;
            })
            setPosts(posts)
        });
    }

    useEffect(() => {
        getPosts();
    }, []);

    return (
        <>
            <Jumbotron title="Title of a longer featured blog post" text="Multiple lines of text that form the lede, informing new readers quickly
                        and efficiently about what’s most interesting in this post’s contents."/>

            <div className="row mb-2">
                {posts.map((post) => (
                    <div className="col-md-6" key={post.id}>
                        <div
                            className="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div className="col p-4 d-flex flex-column position-static">
                                <h3 className="mb-0">{post.title}</h3>
                                <div className="mb-1 text-body-secondary">Nov 12</div>
                                <p className="card-text mb-auto">This is a wider card with supporting text below as a
                                    natural lead-in to additional content.</p>
                                <a href="#" className="icon-link gap-1 icon-link-hover stretched-link">
                                    Continue reading
                                </a>
                            </div>
                            <div className="col-auto d-none d-lg-block">
                                <img src={ post.thumbnail ? post.thumbnail : 'https://placehold.co/150' } alt="thumbnail"/>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

        </>
    )
}
