// vue/src/components/Jumbotron.vue
<script>
export default {
  name: 'Jumbotron',
  props: {
    title: "",
    text: ""
  }
}
</script>

<template>
  <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
      <h1 class="display-4 fst-italic">{{ title }}</h1>
      <p class="lead my-3">{{ text }}</p>
      <p class="lead mb-0"><a href="#" class="text-body-emphasis fw-bold">Continue reading...</a>
      </p>
    </div>
  </div>
</template>

// react/src/layout/Jumbotron.tsx
interface Props {
    title: string;
    text: string;
}
export function Jumbotron(props: Props) {
    return (
        <>
            <div className="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
                <div className="col-lg-6 px-0">
                    <h1 className="display-4 fst-italic">{props.title}</h1>
                    <p className="lead my-3">{props.text}</p>
                    <p className="lead mb-0"><a href="#" className="text-body-emphasis fw-bold">Continue reading...</a>
                    </p>
                </div>
            </div>
        </>
    );
}
